platform :ios, '15.0'

pod 'AppLovinSDK','13.6.4'
pod 'Google-Mobile-Ads-SDK', '13.11.0'

{{#applovin.MintegralAdapter}}
pod 'AppLovinMediationMintegralAdapter', '8.1.7.0.1'
{{/applovin.MintegralAdapter}}

{{#applovin.InMobiAdapter}}
pod 'AppLovinMediationInMobiAdapter', '11.5.0.0'
{{/applovin.InMobiAdapter}}

{{#applovin.IronSourceAdapter}}
pod 'AppLovinMediationIronSourceAdapter', '9.6.1.0.0'
{{/applovin.IronSourceAdapter}}

{{#applovin.VungleAdapter}}
pod 'AppLovinMediationVungleAdapter', '7.7.8.0'
{{/applovin.VungleAdapter}}

{{#applovin.FacebookAdapter}}
pod 'AppLovinMediationFacebookAdapter', '6.22.0.4'
{{/applovin.FacebookAdapter}}

{{#applovin.MyTargetAdapter}}
pod 'AppLovinMediationMyTargetAdapter', '5.43.0.0'
{{/applovin.MyTargetAdapter}}

{{#applovin.UnityAdsAdapter}}
pod 'AppLovinMediationUnityAdsAdapter', '4.21.0.0'
{{/applovin.UnityAdsAdapter}}

{{#applovin.OguryPresageAdapter}}
pod 'AppLovinMediationOguryPresageAdapter', '5.3.1.0'
{{/applovin.OguryPresageAdapter}}

{{#applovin.FyberAdapter}}
pod 'AppLovinMediationFyberAdapter', '8.5.0.0'
{{/applovin.FyberAdapter}}

{{#applovin.GoogleAdManagerAdapter}}
pod 'AppLovinMediationGoogleAdManagerAdapter', '13.11.0.0'
{{/applovin.GoogleAdManagerAdapter}}

{{#applovin.GoogleAdapter}}
pod 'AppLovinMediationGoogleAdapter', '13.11.0.0'
{{/applovin.GoogleAdapter}}

{{#applovin.ChartboostAdapter}}
pod 'AppLovinMediationChartboostAdapter', '9.14.2.0'
{{/applovin.ChartboostAdapter}}

{{#applovin.ByteDanceAdapter}}
pod 'AppLovinMediationByteDanceAdapter', '8.3.0.8.0'
{{/applovin.ByteDanceAdapter}}

{{#applovin.BidMachineAdapter}}
pod 'AppLovinMediationBidMachineAdapter', '3.8.2.0.0'
{{/applovin.BidMachineAdapter}}

{{#applovin.YandexAdapter}}
pod 'AppLovinMediationYandexAdapter', '8.6.0.0'
{{/applovin.YandexAdapter}}